# YAML

sicer:
    outdir: /home/denovo/AU/Research/Data/tools_output/sicer
    path: /home/denovo/AU/Research/Tools/sicer
    projname: diff_e2_vh

#manorm:
#    outdir: /home/denovo/AU/Research/Data/tools_output/manorm
#    path: /home/denovo/AU/Research/Tools/manorm
#    projname: diff_e2_vh

macs2:
    outdir: /home/denovo/AU/Research/Data/tools_output/macs2
    path: /home/denovo/miniconda/bin
    projname: diff_e2_vh

chipdiff:
    outdir: /home/denovo/AU/Research/Data/tools_output/chipdiff
    chromosomes: /home/denovo/AU/Research/Data/bed/chrom_descr.txt
    path: /home/denovo/AU/Research/Tools/chipdiff
    projname: diff_e2_vh

zinbra:
    outdir: /home/denovo/AU/Research/Data/tools_output/zinbra
    path:   /home/denovo/AU/Research/Tools/zinbra
    projname: diff_e2_vh
    only_chr: chr11